#!/usr/bin/env python3
import subprocess
import shutil
import re
from pathlib import Path

# --- Configuration & Paths ---
HOME = Path.home()
CONFIG = HOME / ".config"
CACHE = HOME / ".cache"
SCRIPT_DIR = Path(__file__).resolve().parent
STATE_FILE = CACHE / "hypr_performance_state.json"

HYPR_DIR = CONFIG / "hypr"
HYPR_CONF = HYPR_DIR / "hyprland.conf"
PERF_CONF = HYPR_DIR / "performance-mode.conf"
ACTIVE_COLORS = HYPR_DIR / "active-colors.conf"
VARIABLES_CONF = HYPR_DIR / "variables.conf"

WAYBAR_MINI_DIR = CONFIG / "waybar-mini"
WAYBAR_CONFIG = WAYBAR_MINI_DIR / "config.jsonc"
WAYBAR_STYLE = WAYBAR_MINI_DIR / "style.css"

KITTY_CONF = CONFIG / "kitty/kitty.conf"
KITTY_MINI_INC = CONFIG / "kitty/waybar-mini.conf"
KITTY_MINI_SRC = WAYBAR_MINI_DIR / "kitty-mini.conf"
KILL_SHELL = SCRIPT_DIR / "kill_shell.sh"
RESTART_SHELL = SCRIPT_DIR / "restart_shell.sh"


def run(cmd):
    subprocess.Popen(
        cmd,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        start_new_session=True,
    )


def run_sync(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)


def read_hypr_variable(name, fallback):
    if not VARIABLES_CONF.exists():
        return fallback

    pattern = re.compile(rf"^\${re.escape(name)}\s*=\s*(.+?)\s*(?:#.*)?$")
    for line in VARIABLES_CONF.read_text().splitlines():
        match = pattern.match(line.strip())
        if match:
            return match.group(1).strip()

    return fallback


def hypr_keyword(option, value):
    run_sync(["hyprctl", "keyword", option, str(value)])


def apply_hypr_runtime_mode(enable):
    if enable:
        values = {
            "general:gaps_in": 0,
            "general:gaps_out": 0,
            "general:gaps_workspaces": 0,
            "general:border_size": 2,
            "decoration:rounding": 0,
            "decoration:shadow:enabled": "false",
            "decoration:blur:enabled": "false",
            "animations:enabled": "false",
        }
    else:
        values = {
            "general:gaps_in": read_hypr_variable("windowGapsIn", 10),
            "general:gaps_out": read_hypr_variable("windowGapsOut", 20),
            "general:gaps_workspaces": read_hypr_variable("workspaceGaps", 20),
            "general:border_size": read_hypr_variable("windowBorderSize", 2),
            "decoration:rounding": read_hypr_variable("windowRounding", 8),
            "decoration:shadow:enabled": read_hypr_variable("shadowEnabled", "true"),
            "decoration:blur:enabled": read_hypr_variable("blurEnabled", "true"),
            "animations:enabled": "true",
        }

    for option, value in values.items():
        hypr_keyword(option, value)


def ensure_hypr_source():
    if not HYPR_CONF.exists():
        return
    content = HYPR_CONF.read_text()
    if "performance-mode.conf" not in content:
        with open(HYPR_CONF, "a") as f:
            f.write(f"\n# Performance Mode Overrides\nsource = {PERF_CONF}\n")


def enable_ultra():
    ensure_hypr_source()
    PERF_CONF.write_text("""
# AUTOMATICALLY GENERATED BY PERFORMANCE SCRIPT
$blurEnabled = false
$shadowEnabled = false
$windowRounding = 0
$workspaceGaps = 0
$windowGapsIn = 0
$windowGapsOut = 0
$singleWindowGapsOut = 0
$singleWindowGapsIn = 0
$windowBorderSize = 2

general {
    gaps_in = 0
    gaps_out = 0
    gaps_workspaces = 0
    border_size = 2
}
decoration {
    rounding = 0
    shadow:enabled = false
    blur:enabled = false
}
animations {
    enabled = false
}
windowrulev3 = gapsin 0, class:.*
windowrulev3 = gapsout 0, class:.*
""")

    # run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita-dark"])
    # run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", "Adwaita"])

    if KITTY_CONF.exists():
        content = KITTY_CONF.read_text()
        if "include waybar-mini.conf" not in content:
            content += "\ninclude waybar-mini.conf\n"
        content = re.sub(
            r"background_opacity\s+[\d\.]+", "background_opacity 1.0", content
        )
        KITTY_CONF.write_text(content)
        if KITTY_MINI_SRC.exists():
            shutil.copy(KITTY_MINI_SRC, KITTY_MINI_INC)
        run(["kitty", "@", "set-background-opacity", "--all", "1.0"])

    run(["fish", "-c", "set -Ux fish_color_scheme Snowman"])

    run_sync([str(KILL_SHELL)])
    apply_hypr_runtime_mode(True)
    run(["waybar", "-c", str(WAYBAR_CONFIG), "-s", str(WAYBAR_STYLE)])
    run(["notify-send", "Performance", "ULTRA Mode Enabled", "-t", "1000"])


def disable_ultra():
    PERF_CONF.write_text("""# Performance Mode Disabled
$singleWindowGapsOut = 10
$singleWindowGapsIn = 5
""")

    run(
        [
            "gsettings",
            "set",
            "org.gnome.desktop.interface",
            "gtk-theme",
            "adw-gtk3-dark",
        ]
    )
    run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", "kora-grey"])

    if KITTY_CONF.exists():
        content = KITTY_CONF.read_text()
        content = content.replace("include waybar-mini.conf", "")
        content = re.sub(
            r"background_opacity\s+[\d\.]+", "background_opacity 0.75", content
        )
        KITTY_CONF.write_text(content)
        if KITTY_MINI_INC.exists():
            KITTY_MINI_INC.unlink()
        run(["kitty", "@", "set-background-opacity", "--all", "0.75"])

    run(["fish", "-c", "set -Ux fish_color_scheme Dracula"])

    run_sync(["killall", "waybar"])
    apply_hypr_runtime_mode(False)
    run([str(RESTART_SHELL)])
    run(["notify-send", "Performance", "Normal Mode Restored", "-t", "1000"])


if __name__ == "__main__":
    if not STATE_FILE.exists():
        enable_ultra()
        STATE_FILE.write_text("ultra")
    else:
        disable_ultra()
        if STATE_FILE.exists():
            STATE_FILE.unlink()
