# Black Theme for Performance Mode

$background = rgba(000000ff)
$foreground = rgba(ffffffff)

$color0 = rgba(282a36ff) # bg
$color1 = rgba(ff5555ff) # red
$color2 = rgba(50fa7bff) # green
$color3 = rgba(f1fa8cff) # yellow
$color4 = rgba(bd93f9ff) # purple
$color5 = rgba(ff79c6ff) # magenta
$color6 = rgba(8be9fdff) # cyan
$color7 = rgba(f8f8f2ff) # fg
$color8 = rgba(6272a4ff) # comment
$color9 = $color1
$color10 = $color2
$color11 = $color3
$color12 = $color4
$color13 = $color5
$color14 = $color6
$color15 = $color7

general:col.active_border = $color4
general:col.inactive_border = $color8

