color0 #1b2023
color1 #fd4663
color2 #70d6e6
color3 #799ddd
color4 #8c81d5
color5 #92e0ec
color6 #96b4e9
color7 #f2f3f3
color8 #5b6d6f
color9 #fd4663
color10 #70d6e6
color11 #799ddd
color12 #8c81d5
color13 #92e0ec
color14 #96b4e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #1b2023
background            #1b2023
foreground            #f2f3f3
selection_foreground  #afb5b6
selection_background  #242b2e
active_border_color   #70d6e6
inactive_border_color #242b2e
url_color             #70d6e6

active_tab_foreground   #182325
active_tab_background   #70d6e6
inactive_tab_foreground #afb5b6
inactive_tab_background #242b2e
cursor_trail_color      #afb5b6
